# Generated by Django 4.1 on 2023-03-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.IntegerField(default='')),
                ('number2', models.IntegerField(default='')),
                ('answer', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
